create table user_info
(
   user_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL ,                     
   user_name                 VARCHAR(20) NOT NULL ,
   age                   BIGINT NOT NULL , 
   primary key (user_id)
)/*engine=innodb default charset=utf8*/;
/*insert into user_info (user_name,age) VALUES('xiebiao',100);*/
